### ISSUE TITLE
How can I use this?

### ISSUE THREAD

**Issue by SaLiXeM** [keeler/sifty#6] opened 2017-12-22 23:28 UTC
Hello,

I just downloaded this extension but I have no idea how this thing works. There is no options page, and clicking the toolbar icon does nothing!

**Comment by keeler** [comment] 2017-12-23 08:33
Hey there, that sucks! Sorry it isn't working for you, hopefully with a bit more info I can get this fixed.

How it's supposed to work:
If you right-click an image and choose either "view image" or "open image in new tab", those image tabs can be downloaded then closed by clicking the sifty toolbar button. Same goes for video tabs and audio tabs.

What happens when you do this?
1) Open a new Firefox window.
2) Hit F12, click Console tab.
3) Open http://sipi.usc.edu/database/preview/textures/1.5.02.png in a new tab.
4) Click the sifty toolbar button.

Can you take a screenshot of any console logs that appear, or paste them here?

There's no options page because I haven't built one yet. I'd love to hear what kind of options you'd like to find there, though.

When you click the toolbar button and there's nothing for the plugin to do you should still see a notification that says something like "no items found". Does your browser console show any logs in this situation?

**Comment by keeler** [comment] 2017-12-25 00:40
@SaLiXeM

**Comment by keeler** [comment] 2017-12-25 00:40
Sorry closed it on accident!

**Comment by keeler** [comment] 2018-03-15 15:28
@SaLiXeM closing this, reopen if you want to pursue.

**Closed by keeler** 2018-03-15 15:28 UTC

**Comment by keeler** [comment] 2019-02-13 01:12
Opened issue https://github.com/keeler/sifty/issues/7 to enable searching behavior which might have been the expected behavior here.
